### ISSUE TITLE
Possible issue

### ISSUE THREAD

**Issue by Typhon042** [GreyHak/dsp-csv-gen#13]
I noticed the icon, not showing in the game and no document being generated.  Not sure if this is a mod conflict issue or something going on with just me.

Current mods I use are in this order.
BepInEx
IcarusColorPicker
DSP Star Sector Resrouce Spreadsheet Generator
LDBTool
FreeFoundations
WaterElectrolysis
Mecha Energy Usage Multiplier
DSPCheats (planning on disabling and removing this one regardless)

**Comment by GreyHak** [comment]
Thank you for the report @Typhon042 .  Could you please respond with your BepInEx log file?  It's probably located at something like "C:\Program Files (x86)\Steam\steamapps\common\Dyson Sphere Program\BepInEx\LogOutput.log"
You should be able to attach the file to a new comment on this issue.  Thank you.

**Comment by GreyHak** [comment]
@Typhon042 An issue has been identified in the spreadsheet generation mod caused by Dyson Sphere Program's recent updated release.  A fix for that problem has just been released, v3.0.2.  Could you please [download](https://dsp.thunderstore.io/package/GreyHak/DSP_Star_Sector_Resource_Spreadsheet_Generator/) the updated mod, try it out, and reply with how it worked for you?  The known problem doesn't exactly match your description.  So if it still doesn't work, please attach the BepInEx log as requested above.  Thank you.

**Comment by GreyHak** [comment]
It's been 9 days since I requested more information.  Please open a new ticket if this is still an issue.
