### ISSUE TITLE
Star Luminosity values do not correspond to ingame ones

### ISSUE THREAD

**Issue by PeterLyaskovskyA1QA** [GreyHak/dsp-csv-gen#4]
So basically as headline says: CSV values are several times higher than ingame ones.
Example (see attached files): η Leonis Minoris 16.1048 in CSV, 2.502 ingame.
I have a feeling that 16+ value is what game has, but there's some kind of simple math that provides ingame value using maybe star radius or smth else. If that's a fact - simply knowing that logic would be enough, Excel will do the rest. Thanks!

[DSP_Res.zip](https://github.com/GreyHak/dsp-csv-gen/files/6027251/DSP_Res.zip)
![Leonis Minoris](https://user-images.githubusercontent.com/45570923/108812624-81654380-75c0-11eb-971f-7e37d7b9f699.jpg)

**Comment by GreyHak** [comment]
Thank you for the report @PeterLyaskovskyA1QA.  The CVS contains the star luminosity.  It turns out that the display you're looking at is showing the dyson luminosity.  The calculation in-game from star luminosity to dyson luminosity is:
* dysonLuminosity = Mathf.Round((float)Math.Pow((double)starLuminosity, 0.33000001311302185) * 1000f) / 1000f

So basically just raise the value in the csv to the power of 0.33, and you'll get the value you're looking for.
Do you have a suggestion how I could correct this in the mod?  I'm thinking replace the Star Luminosity column with Dyson Luminosity?

**Comment by PeterLyaskovskyA1QA** [comment]
> Do you have a suggestion how I could correct this in the mod? I'm thinking replace the Star Luminosity column with Dyson Luminosity?

Yep, this seems like the most logical and "common sense" way to fix this one. I bet ordinary users like me would like to see in the CSV your mod returns the same number we see in game. Thanks in advance, I suppose the fix should be easy to make! =)

**Comment by GreyHak** [comment]
I've pushed the update to GitHub.  It will go into the next release.

**Comment by GreyHak** [comment]
@PeterLyaskovskyA1QA Should be fix in release v1.2.0
