### ISSUE TITLE
Star Dyson Lumino not same as in game

### ISSUE THREAD

**Issue by Scheballs** [GreyHak/dsp-csv-gen#5]
I was wondering if the value I see in the Star Luminosity aka Star Dyson Luminosity is actually the same as the value we see in game? 
I am seeing different values. 

From scientific articles it looks like it's actually related to the Star Radius and Temperature so I was wondering if that is required to give the same value we see in game for Star Luminosity. 

I know this sounds like partly an enhancement request but I am curious if we need the radius and temp to return that in game luminosity. 
Thanks! 
![eq_luminosity_full](https://user-images.githubusercontent.com/4333869/109239816-47549700-77a4-11eb-9958-2c8a0e7bffe3.gif)

https://www.atnf.csiro.au/outreach/education/senior/astrophysics/photometry_luminosity.html

"σ is a constant called the Stefan-Boltzmann constant. It has value of σ = 5.67 × 10-8 W m-2 K-4 in SI units. As a star is not a perfect black body we can approximate this relationship as:"

**Comment by GreyHak** [comment]
Thank you for the feedback @Scheballs .  You've used two similar terms, and haven't provided the version your testing.  So let me give you some perspective, and we can try to narrow in on your question.  My apologies if it's more detail than you want, but given your question, I'm confident you can handle it.

The game has three star-related definitions of luminosity (well, three I'll describe here).  When I released the original version of this mod I had a column called "Star Luminosity" and another called "Luminosity".  Another user wrote ticket https://github.com/GreyHak/dsp-csv-gen/issues/4 indicating that my "Star Luminosity" (in the game it's called StarData.luminosity) didn't match what was shown in-game.  I don't believe the column I was providing as "Star Luminosity" is shown in the game anywhere, but I could be mistaken.  So in the latest release, v1.2.0, I replaced "Star Luminosity" with "Star Dyson Luminosity".  It wasn't just a header change, but a change to the data.  In the game this new value is called StarData.dysonLumino and is calculated roughly as (dysonLumino = luminosity^0.33).  I believe it's dysonLumino which you see in the game everywhere.  When I released v1.2.0 I also renamed the "Luminosity" column to "Luminosity on Planet" (without a change to the numerical data) to avoid confusion.

So your question -- indicating that the spreadsheet isn't showing the same luminosity as the game -- suggests you're using a release prior to v1.2.0.  But since you used the term "Star Dyson Luminosity", I'm not so sure.  I'm hoping you thought I just changed the column name, and didn't realize I changed the data too.  Can you please confirm that you are using the latest v1.2.0, and that you see a discrepency between the spreadsheet's "Star Dyson Luminosity" (generated by v1.2.0) and what you see in game?  Thank you.

**Comment by Scheballs** [comment]
Thanks for the great answer. My fault because I saw your new release 1.2.0 and was hoping to see a different value but after a new seed loaded it still wasn't matched. Then I looked deeper and realized the version installed was still 1.1.4. The r2modman mod installer wouldn't let me get your newest version. I've since manually downloaded 1.2.0 now. 

So it that power to 0.33 formula something you find from the game code? 

My other question is if the Star Temp and Radius are available to you? Not sure yet if maybe those are needed to derive the in game luminosity. Perhaps the Dyson Lumino provided is what game needs to return the power of your sphere or swarms?

**Comment by GreyHak** [comment]
@Scheballs So good to hear.  The game code is:
- dysonLuminosity = Mathf.Round((float)Math.Pow((double)starLuminosity, 0.33000001311302185) * 1000f) / 1000f

Yes, temperature and about 8 different radii are available in the game for the stars.  I didn't see any value in having them.  They aren't used for calculating luminosity.  If you want any star or planet details added, just let me know.

**Comment by Scheballs** [comment]
Ooo Nice thank you for that. So it looks like this issue is fixed in 1.2.0 fixed compared to what I see in 1.1.4. 
Do you have any insights on how your dyson sphere power output is calculated from the Star Dyson Luminosity?

**Comment by GreyHak** [comment]
@Scheballs I didn't have any insight, but I've just looked at the code, and here's my analysis.
- It looks like the sail swarm energy generation per tick is sailCount * dysonLumino * 400
- The dyson shell energy generation is more complicated, it looks to be per tick: (numFrames * 1500 + numNodes * 1500 + numCells * 300) * dysonLumino

I believe the game attempts to achieve 60 ticks per second.

**Comment by GreyHak** [comment]
According to Rayanth,
- game tick rate is 60/s. If the "400" in the game code for swarm sails is in Joules per Tick, then they would only give 24kW per sail. Per patch 5651, they give 36kW/sail on a 1.0 luminosity star, 1.5x more. I suspect there's a multiplier somewhere in the code
